name: Test Laravel 11

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.1', '8.2']

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, tokenizer, xml, ctype
          coverage: none

      - name: Install Laravel 11 dependencies
        run: composer require "laravel/framework:11.*" --no-update
        env:
          COMPOSER_ALLOW_SUPERUSER: 1

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        env:
          COMPOSER_ALLOW_SUPERUSER: 1

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit
