name: Run PHPUnit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit
  label:
    needs: test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Add label to PR
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "tests passed"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
